#' ---
# title: "Data Pull and Cleaning Script"
#' ---

# ============================================================================
# GENERATED BY CLAUDE CODE
# FOR DEMONSTRATION PURPOSES ONLY
# ============================================================================

library(tidyverse)
library(lubridate)
library(DBI)
library(httr)
library(jsonlite)

# Set date range for data pull
start_date <- as.Date("2021-01-04")
end_date <- as.Date("2023-12-25")

# ============================================================================
# 1. PULL SALES DATA FROM DATABASE
# ============================================================================

# Connect to sales database
con <- dbConnect(
  RPostgres::Postgres(),
  host = Sys.getenv("DB_HOST"),
  port = 5432,
  dbname = "sales_db",
  user = Sys.getenv("DB_USER"),
  password = Sys.getenv("DB_PASSWORD")
)

# Query weekly sales data
sales_data <- dbGetQuery(
  con,
  "
  SELECT
    date_trunc('week', sale_date)::date AS date,
    SUM(revenue) AS sales_revenue,
    SUM(base_sales) AS base_sales
  FROM sales_transactions
  WHERE sale_date >= $1 AND sale_date <= $2
    AND country = 'US'
    AND status = 'completed'
  GROUP BY date_trunc('week', sale_date)
  ORDER BY date
",
  params = list(start_date, end_date)
)

# Close connection
dbDisconnect(con)

# ============================================================================
# 2. PULL MARKETING SPEND DATA FROM APIs
# ============================================================================

# Function to pull data from marketing API
pull_marketing_api <- function(channel, start_date, end_date) {
  response <- GET(
    url = "https://api.marketing-platform.com/v2/spend",
    query = list(
      channel = channel,
      start_date = start_date,
      end_date = end_date,
      granularity = "weekly"
    ),
    add_headers(
      Authorization = paste("Bearer", Sys.getenv("MARKETING_API_KEY"))
    )
  )

  if (status_code(response) == 200) {
    content(response, as = "parsed") %>%
      bind_rows() %>%
      mutate(channel = channel)
  } else {
    warning(sprintf(
      "Failed to pull %s data: %s",
      channel,
      status_code(response)
    ))
    return(NULL)
  }
}

# Pull spend data for each channel
channels <- c(
  "tv",
  "radio",
  "print",
  "paid_search",
  "display_ads",
  "social_media",
  "email"
)

marketing_spend <- map_dfr(
  channels,
  ~ {
    Sys.sleep(0.5) # Rate limiting
    pull_marketing_api(.x, start_date, end_date)
  }
)

# Reshape to wide format
marketing_spend_wide <- marketing_spend %>%
  select(date, channel, spend) %>%
  pivot_wider(
    names_from = channel,
    values_from = spend,
    names_glue = "{channel}_spend"
  )

# ============================================================================
# 3. PULL ATTRIBUTION DATA FROM CSV FILES
# ============================================================================

# Read attribution/contribution data from CSV exports
attribution_files <- list.files(
  path = "data/raw/attribution",
  pattern = "attribution_.*\\.csv$",
  full.names = TRUE
)

attribution_data <- map_dfr(
  attribution_files,
  ~ {
    read_csv(.x, col_types = cols()) %>%
      mutate(file_source = basename(.x))
  }
)

# Clean and aggregate attribution data
attribution_clean <- attribution_data %>%
  select(date, channel, contribution = attributed_revenue) %>%
  group_by(date, channel) %>%
  summarize(
    contribution = sum(contribution, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = channel,
    values_from = contribution,
    names_glue = "{channel}_spend_contribution"
  )

# ============================================================================
# 4. PULL PROMOTIONAL DATA FROM GOOGLE SHEETS API
# ============================================================================

# Connect to Google Sheets (using googlesheets4 package)
# In reality, you'd authenticate first
promotions_data <- read_sheet(
  ss = "https://docs.google.com/spreadsheets/d/SHEET_ID_HERE",
  sheet = "Promotions",
  col_types = "Dcnn" # Date, character, numeric, numeric
) %>%
  select(date, promotion_type, promotion_active, promotion_lift) %>%
  mutate(
    promotion = if_else(promotion_active == 1, 1, 0),
    promotion_lift = if_else(is.na(promotion_lift), 0, promotion_lift)
  ) %>%
  select(date, promotion, promotion_lift)

# ============================================================================
# 5. PULL COMPETITOR DATA FROM EXTERNAL API
# ============================================================================

# Pull competitor activity from market research API
competitor_response <- GET(
  url = "https://api.marketresearch.com/v1/competitor-activity",
  query = list(
    industry = "retail",
    start_date = start_date,
    end_date = end_date,
    frequency = "weekly"
  ),
  add_headers(
    "X-API-Key" = Sys.getenv("MARKET_RESEARCH_API_KEY")
  )
)

competitor_data <- content(competitor_response, as = "parsed") %>%
  bind_rows() %>%
  select(
    date,
    competitor_activity = activity_score,
    competitor_impact = impact_revenue
  ) %>%
  mutate(
    competitor_activity = if_else(competitor_activity > 5, 1, 0),
    competitor_impact = if_else(is.na(competitor_impact), 0, competitor_impact)
  )

# ============================================================================
# 6. COMBINE ALL DATA SOURCES
# ============================================================================

# Start with sales data as the base
combined_data <- sales_data %>%
  # Join marketing spend
  left_join(marketing_spend_wide, by = "date") %>%
  # Join attribution data
  left_join(attribution_clean, by = "date") %>%
  # Join promotions
  left_join(promotions_data, by = "date") %>%
  # Join competitor data
  left_join(competitor_data, by = "date")

# ============================================================================
# 7. DATA CLEANING AND FEATURE ENGINEERING
# ============================================================================

final_data <- combined_data %>%
  # Add date features
  mutate(
    week = row_number(),
    year = year(date),
    quarter = quarter(date),
    month = month(date),
    week_of_year = isoweek(date)
  ) %>%
  # Fill missing values with 0 for spend columns
  mutate(across(ends_with("_spend"), ~ replace_na(.x, 0))) %>%
  mutate(across(ends_with("_contribution"), ~ replace_na(.x, 0))) %>%
  # Calculate total marketing metrics
  mutate(
    total_marketing_spend = tv_spend +
      radio_spend +
      print_spend +
      paid_search_spend +
      display_ads_spend +
      social_media_spend +
      email_spend,
    total_marketing_contribution = tv_spend_contribution +
      radio_spend_contribution +
      print_spend_contribution +
      paid_search_spend_contribution +
      display_ads_spend_contribution +
      social_media_spend_contribution +
      email_spend_contribution
  ) %>%
  # Calculate week-over-week changes
  mutate(
    sales_wow_change = (sales_revenue - lag(sales_revenue)) /
      lag(sales_revenue),
    spend_wow_change = (total_marketing_spend - lag(total_marketing_spend)) /
      lag(total_marketing_spend)
  ) %>%
  # Add holiday indicator
  mutate(
    holiday_week = if_else(
      week_of_year %in% c(1, 2, 27, 28, 45, 46, 47, 49, 50, 51, 52, 53),
      1,
      0
    )
  ) %>%
  # Ensure all numeric columns have proper types
  mutate(across(where(is.numeric), ~ round(.x, 2))) %>%
  # Reorder columns
  select(
    date,
    week,
    year,
    quarter,
    month,
    week_of_year,
    tv_spend,
    radio_spend,
    print_spend,
    paid_search_spend,
    display_ads_spend,
    social_media_spend,
    email_spend,
    tv_spend_contribution,
    radio_spend_contribution,
    print_spend_contribution,
    paid_search_spend_contribution,
    display_ads_spend_contribution,
    social_media_spend_contribution,
    email_spend_contribution,
    base_sales,
    promotion,
    promotion_lift,
    competitor_activity,
    competitor_impact,
    sales_revenue,
    total_marketing_spend,
    total_marketing_contribution,
    sales_wow_change,
    spend_wow_change,
    holiday_week
  ) %>%
  # Arrange by date
  arrange(date)

# ============================================================================
# 8. DATA QUALITY CHECKS
# ============================================================================

# Check for missing values
missing_summary <- final_data %>%
  summarise(across(everything(), ~ sum(is.na(.x)))) %>%
  pivot_longer(
    everything(),
    names_to = "column",
    values_to = "missing_count"
  ) %>%
  filter(missing_count > 0)

if (nrow(missing_summary) > 0) {
  warning("Missing values detected:")
  print(missing_summary)
}

# Check for negative values in spend/revenue columns
negative_check <- final_data %>%
  filter(if_any(ends_with(c("_spend", "_revenue")), ~ .x < 0))

if (nrow(negative_check) > 0) {
  warning("Negative values detected in spend/revenue columns")
}

# Check date continuity
date_gaps <- final_data %>%
  mutate(expected_next_date = date + days(7)) %>%
  filter(lead(date) != expected_next_date)

if (nrow(date_gaps) > 0) {
  warning("Date gaps detected in the data")
}

# ============================================================================
# 9. EXPORT FINAL DATA
# ============================================================================

# Create data directory if it doesn't exist
dir.create("data", showWarnings = FALSE)

# Write to CSV
write_csv(final_data, "data/synthetic-marketing-sales.csv")

# Write metadata
metadata <- list(
  generated_at = Sys.time(),
  date_range = c(min(final_data$date), max(final_data$date)),
  n_weeks = nrow(final_data),
  channels = channels,
  sources = c(
    "sales_db",
    "marketing_api",
    "attribution_csv",
    "google_sheets",
    "market_research_api"
  )
)

write_json(metadata, "data/data-pull-metadata.json", pretty = TRUE)

# Print summary
cat("\n=== Data Pull Complete ===\n")
cat(sprintf("Rows: %d\n", nrow(final_data)))
cat(sprintf(
  "Date Range: %s to %s\n",
  min(final_data$date),
  max(final_data$date)
))
cat(sprintf(
  "Total Marketing Spend: $%.2fM\n",
  sum(final_data$total_marketing_spend) / 1000
))
cat(sprintf(
  "Total Sales Revenue: $%.2fM\n",
  sum(final_data$sales_revenue) / 1000
))
cat(sprintf("Output: %s\n", "data/synthetic-marketing-sales.csv"))
